[[eventadmin-component]]
== OSGi EventAdmin Component

*Available as of Camel version 2.6*

The `eventadmin` component can be used in an OSGi environment to receive
OSGi EventAdmin events and process them.

### Dependencies

Maven users need to add the following dependency to their `pom.xml`

[source,xml]
-------------------------------------------
<dependency>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-eventadmin</artifactId>
  <version>${camel-version}</version>
</dependency>
-------------------------------------------

where `${camel-version`} must be replaced by the actual version of Camel
(2.6.0 or higher).

### URI format

[source,xml]
--------------------------
eventadmin:topic[?options]
--------------------------

where `topic` is the name of the topic to listen too.

### URI options

// component options: START
The OSGi EventAdmin component supports 1 options, which are listed below.



[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *bundleContext* (common) | The OSGi BundleContext is automatic injected by Camel |  | BundleContext
|===
// component options: END

// endpoint options: START
The OSGi EventAdmin endpoint is configured using URI syntax:

----
eventadmin:topic
----

with the following path and query parameters:

==== Path Parameters (1 parameters):


[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *topic* | Name of topic to listen or send to |  | String
|===


==== Query Parameters (1 parameters):


[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *send* (common) | Whether to use 'send' or 'synchronous' deliver. Default false (async delivery) | false | boolean
|===
// endpoint options: END

### Message headers

[width="100%",cols="10%,10%,80%",options="header",]
|=======================================================================
|Name |Type |Message |Description
| | |
|=======================================================================

### Message body

The `in` message body will be set to the received Event.

### Example usage

[source,xml]
------------------------------
<route>
    <from uri="eventadmin:*"/>
    <to uri="stream:out"/>
</route>
------------------------------
