[[paxlogging-component]]
== OSGi PAX Logging Component

*Available as of Camel version 2.6*

The `paxlogging` component can be used in an OSGi environment to receive
http://wiki.ops4j.org/display/paxlogging/Pax+Logging[PaxLogging] events
and process them.

### Dependencies

Maven users need to add the following dependency to their `pom.xml`

[source,xml]
-------------------------------------------
<dependency>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-paxlogging</artifactId>
  <version>${camel-version}</version>
</dependency>
-------------------------------------------

where `${camel-version`} must be replaced by the actual version of Camel
(2.6.0 or higher).

### URI format

[source,xml]
-----------------------------
paxlogging:appender[?options]
-----------------------------

where `appender` is the name of the pax appender that need to be
configured in the PaxLogging service configuration.

### URI options



// component options: START
The OSGi PAX Logging component supports 1 options, which are listed below.



[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *bundleContext* (consumer) | The OSGi BundleContext is automatic injected by Camel |  | BundleContext
|===
// component options: END




// endpoint options: START
The OSGi PAX Logging endpoint is configured using URI syntax:

----
paxlogging:appender
----

with the following path and query parameters:

==== Path Parameters (1 parameters):


[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *appender* | *Required* Appender is the name of the pax appender that need to be configured in the PaxLogging service configuration. |  | String
|===


==== Query Parameters (0 parameters):


The OSGi PAX Logging endpoint has no query parameters.
// endpoint options: END


### Message body

The `in` message body will be set to the received PaxLoggingEvent.

### Example usage

[source,xml]
----------------------------------
<route>
    <from uri="paxlogging:camel"/>
    <to uri="stream:out"/>
</route>
----------------------------------

Configuration:

[source,java]
----------------------------------------------------------
log4j.rootLogger=INFO, out, osgi:VmLogAppender, osgi:camel
----------------------------------------------------------
